name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Flask app Docker image
      run: |
        cd vote
        docker build -t yourusername/flask-app:latest .

    - name: Build Node.js app Docker image
      run: |
        cd result
        docker build -t yourusername/node-app:latest .

    - name: Build .NET Worker Docker image
      run: |
        cd worker
        docker build -t yourusername/dotnet-worker:latest .

    - name: Push Flask app Docker image
      run: docker push yourusername/flask-app:latest

    - name: Push Node.js app Docker image
      run: docker push yourusername/node-app:latest

    - name: Push .NET Worker Docker image
      run: docker push yourusername/dotnet-worker:latest

